# Generated by Django 3.0.5 on 2020-07-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_place', models.CharField(max_length=100)),
                ('to_place', models.CharField(max_length=100)),
                ('travel_date_time', models.DateTimeField(auto_now=True)),
                ('no_of_seats', models.IntegerField()),
                ('luggage_quantity', models.IntegerField()),
                ('is_flexible', models.BooleanField(default=False)),
                ('flexible_from_time', models.DateTimeField(auto_now=True)),
                ('flexible_to_time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=20, verbose_name=['CONFIRM', 'PENDING', 'EXPIRED'])),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
