# Generated by Django 3.0.5 on 2020-07-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_ride', '0002_auto_20200723_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderequest',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
