# Generated by Django 2.2.1 on 2020-07-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_ride', '0003_auto_20200723_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_place', models.CharField(max_length=100)),
                ('to_place', models.CharField(max_length=100)),
                ('travel_date_time', models.DateTimeField(auto_now=True)),
                ('is_flexible', models.BooleanField(default=False)),
                ('flexible_from_time', models.DateTimeField(auto_now=True)),
                ('flexible_to_time', models.DateTimeField(auto_now=True)),
                ('no_of_assets', models.IntegerField()),
                ('asset_type', models.CharField(max_length=100)),
                ('asset_sensitivity', models.CharField(max_length=100, verbose_name=['HIGHLY_SENSITIVE', 'SENSITIVE', 'NORMAL'])),
                ('whom_to_deliver', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200, null=True, verbose_name=['CONFIRM', 'PENDING', 'EXPIRED'])),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
