# Generated by Django 2.2.1 on 2020-08-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_ride', '0005_rideshare'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareTravelInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_place', models.CharField(max_length=100)),
                ('to_place', models.CharField(max_length=100)),
                ('travel_date_time', models.DateTimeField(auto_now=True)),
                ('is_flexible', models.BooleanField(default=False)),
                ('flexible_from_time', models.DateTimeField(auto_now=True)),
                ('flexible_to_time', models.DateTimeField(auto_now=True)),
                ('travel_medium', models.CharField(max_length=100, null=True, verbose_name=['bus', 'car', 'flight', 'ship', 'bike', 'train', 'truck', 'heavy_vehicle'])),
                ('status', models.CharField(max_length=20, null=True, verbose_name=['CONFIRM', 'PENDING', 'EXPIRED'])),
                ('user_id', models.IntegerField(null=True)),
                ('ride_requests', models.IntegerField(null=True)),
                ('assets_quantity', models.IntegerField()),
            ],
        ),
    ]
