# Generated by Django 2.2.1 on 2020-08-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_ride', '0006_sharetravelinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharetravelinfo',
            name='status',
            field=models.CharField(max_length=20, null=True, verbose_name=['ACTIVE', 'EXPIRED']),
        ),
    ]
