# Generated by Django 3.0.5 on 2020-07-21 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_auto_20200721_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_pic',
            new_name='image_url',
        ),
    ]
